#!/usr/bin/perl
# -*- mode: perl; indent-tabs-mode: nil; perl-indent-level: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=perl
#
# Author: Andrew Theurer
#
# rickshaw-source-images: Source (find or build+push) container images for
# benchmarks and tools.  This logic was extracted from rickshaw-run so that
# it can eventually be rewritten as a Python web service.

use strict;
use warnings;
use Cwd;
use File::Basename;
use File::Path qw(make_path);
use JSON::XS;
use Data::Dumper;
use Digest::MD5;
use Getopt::Long;

$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Pair = ' : ';
$Data::Dumper::Useqq = 1;
$Data::Dumper::Indent = 3;

BEGIN {
    if (!(exists $ENV{'TOOLBOX_HOME'} && -d "$ENV{'TOOLBOX_HOME'}/perl")) {
        print "This script requires libraries that are provided by the toolbox project.\n";
        print "Toolbox can be acquired from https://github.com/perftool-incubator/toolbox and\n";
        print "then use 'export TOOLBOX_HOME=/path/to/toolbox' so that it can be located.\n";
        exit 1;
    }
}
use lib "$ENV{'TOOLBOX_HOME'}/perl";
use toolbox::json;
use toolbox::logging;
use toolbox::run;

$toolbox::logging::debug = 0;

# Global state reconstructed from input JSON
my %run;
my $rickshaw_project_dir;
my $config_dir;
my $workshop_build_dir;
my $arch;
my %bench_dirs;
my @utilities;
my $use_workshop;
my $workshop_force_builds;
my $cs_conf_file;
my %cs_conf;
my $workshop_base_cmd;
my %workshop_built_tags;
my %quay_refresh_expiration_tokens;

###############################################################################
# Functions extracted from rickshaw-run
###############################################################################

sub find_files {
    my $path = shift;

    my @files;

    if (-d $path) {
        opendir(DH, $path);
        my @entries = readdir(DH);
        close(DH);
        foreach my $entry (@entries) {
            my $entry_path = $path . '/' . $entry;

            if (($entry =~ /^\.$/) ||
                ($entry =~ /^\.\.$/) ||
                ($entry =~ /^\.git$/) ||
                ($entry =~ /^docs$/) ||
                ($entry =~ /\.md$/) ||
                ($entry =~ /^__pycache__$/) ||
                ($entry =~ /^\.github$/)) {
                next;
            }

            if (-d $entry_path) {
                push(@files, @{find_files($entry_path)})
            } elsif (-e $entry_path) {
                push (@files, $entry_path);
            }
        }
    } elsif (-e $path) {
        push (@files, $path);
    }

    return(\@files);
}

sub calc_image_md5 {
    my $workshop_base_cmd = shift;
    my $userenv_arg = shift;
    die "calc_image_md5(): \$userenv_arg must be defined" if (!defined $userenv_arg);
    my $req_args = shift;
    my $arch_suffix = shift;
    my $userenv = shift;
    my $benchmark_tool = shift;
    my $stage = shift;
    debug_log(sprintf "calc_image_md5(): userenv=%s benchmark/tool=%s stage=%d\n", $userenv, $benchmark_tool, $stage);

    # create an MD5 context
    my $md5 = Digest::MD5->new;

    my $workshop_sub_cmd;
    if (defined $req_args) {
        $workshop_sub_cmd = $workshop_base_cmd . " " . $userenv_arg . " " . $req_args;
    } else {
        $workshop_sub_cmd = $workshop_base_cmd . " " . $userenv_arg;
    }
    my $workshop_config_cmd = $workshop_sub_cmd . " --label config-analysis --dump-config true";
    my $workshop_files_cmd = $workshop_sub_cmd . " --label files-listing --dump-files true";
    debug_log(sprintf "calc_image_md5(): workshop dump-config cmd: %s\n", $workshop_config_cmd);
    (my $cmd, my $cmd_output, my $cmd_rc) = run_cmd($workshop_config_cmd);
    my @config_analysis_output = split(/\n/, $cmd_output);
    if ($cmd_rc > 0) {
        log_print "Workshop dump config failed:\n";
        log_print sprintf "%s\n", join("\n", @config_analysis_output);
        exit 1;
    }
    my $break_line = 0;
    for (my $i=0; $i<scalar(@config_analysis_output); $i++) {
        if ($config_analysis_output[$i] =~ /Config dump:/) {
            $break_line = $i;
        }
    }
    splice(@config_analysis_output, 0, $break_line+1);
    debug_log("calc_image_md5(): workshop dump-config output:\n" . Dumper \@config_analysis_output);

    # The second part of the hash input is the *content* of certain files
    # Start with workshop code and schema, which when changed will
    # trigger new builds.
    my @files = ($run{'workshop-dir'} . "/workshop.pl", $run{'workshop-dir'} . "/schema.json");

    # Add to the file list all the files that workshop identifies
    # as being copied into the userenv
    debug_log(sprintf "calc_image_md5(): workshop dump-files cmd: %s\n", $workshop_files_cmd);
    ($cmd, $cmd_output, $cmd_rc) = run_cmd($workshop_files_cmd);
    my @files_dump_output = split(/\n/, $cmd_output);
    if ($cmd_rc > 0) {
        log_print "Workshop dump files failed:\n";
        log_print sprintf "%s\n", join("\n", @files_dump_output);
        exit 1;
    }
    $break_line = 0;
    for (my $i=0; $i<scalar(@files_dump_output); $i++) {
        if ($files_dump_output[$i] =~ /Files dump:/) {
            $break_line = $i
        }
    }
    splice(@files_dump_output, 0, $break_line+1);
    debug_log("calc_image_md5(): workshop dump-files output:\n" . Dumper \@files_dump_output);

    foreach my $dumped_file (@files_dump_output) {
        if ($dumped_file !~ /^\[VERBOSE\]|^replacing/) {
            debug_log(sprintf "calc_image_md5(): found file from workshop [%s]\n", $dumped_file);

            # look for files that begin with things like 'http://' or
            # 'https://' or similar
            if ($dumped_file =~ /^[a-zA-Z]+:\/\//) {
                debug_log(sprintf "calc_image_md5(): file appears to be remote, attemping to acquire [%s]\n", $dumped_file);

                # reset the MD5 context
                $md5 = Digest::MD5->new;
                $md5->add($dumped_file);
                my $dumped_file_hash = $md5->hexdigest;

                my $dumped_file_hash_filename = "/tmp/rickshaw-run." . $dumped_file_hash;

                my $curl_cmd = 'curl --output ' . $dumped_file_hash_filename .
                               ' --show-error --stderr - --fail-with-body' .
                               ' "' . $dumped_file . '"';

                debug_log(sprintf "calc_image_md5(): attempting to download file via curl [%s -> %s]\n", $dumped_file, $dumped_file_hash_filename);

                ($curl_cmd, my $cmd_status, my $cmd_rc) = run_cmd($curl_cmd);
                if ($cmd_rc == 0) {
                    debug_log(sprintf "calc_image_md5(): download output:\n%s\n", $cmd_status);
                    debug_log(sprintf "calc_image_md5(): download succeeded, replacing filename [%s -> %s]\n", $dumped_file, $dumped_file_hash_filename);
                    $dumped_file = $dumped_file_hash_filename;
                } else {
                    log_print sprintf "calc_image_md5(): Failed to download '%s' for hash calculation:\n", $dumped_file;
                    log_print sprintf "calc_image_md5(): Download command: %s\n", $curl_cmd;
                    log_print sprintf "calc_image_md5(): Download output:\n%s\n", $cmd_status;
                    if (open(DC, "<", $dumped_file_hash_filename)) {
                        my $download_contents = "";
                        while(<DC>) {
                            $download_contents .= $_;
                        }
                        close DC;
                        log_print sprintf "calc_image_md5(): Download contents:\n%s\n", $download_contents;
                    } else {
                        log_print "calc_image_md5(): No download contents available.\n";
                    }
                    exit 1;
                }
            }

            my $real_path = Cwd::realpath($dumped_file);
            if ($real_path ne $dumped_file) {
                debug_log(sprintf "calc_image_md5(): file from workshop [%s] is a link to [%s]\n", $dumped_file, $real_path);
                $dumped_file = $real_path;
            }

            if (-f $dumped_file) {
                push(@files, $dumped_file);
            } elsif (-d $dumped_file) {
                debug_log(sprintf "calc_image_md5(): file from workshop [%s] is actually a directory...\n", $dumped_file);
                my @found_files = @{find_files($dumped_file)};
                foreach my $found_file (@found_files) {
                    debug_log(sprintf "calc_image_md5(): found file [%s]\n", $found_file);
                    push(@files, $found_file);
                }
            }
        }
    }

    my $tag_calc_data = $workshop_build_dir . "tag-calc-data__" . $userenv . "__" . $benchmark_tool . "__stage-" . $stage . ".txt";
    debug_log(sprintf "calc_image_md5(): logging tag calculation data to %s\n", $tag_calc_data);
    my $tag_fh = open_write_text_file($tag_calc_data) || die "Failed to open " . $tag_calc_data . " for writing\n";

    # reset the MD5 context
    $md5 = Digest::MD5->new;

    my $item_header = "# Item #########################################################################\n";
    my $item;

    # First is the Initial hash calc on workshop reqs
    print $tag_fh $item_header . "Workshop Config Output:\n" . join("", @config_analysis_output) . "\n";
    $md5->add(join("", @config_analysis_output));

    # Second is the hashing contents of files
    for my $file (sort @files) {
        debug_log(sprintf "calc_image_md5(): adding '%s' to hash\n", $file);

        print $tag_fh $item_header . "File: " . $file . "\nFile Contents:\n";

        open(my $fh, $file);
        while(<$fh>) {
            print $tag_fh $_;
        }
        print $tag_fh "\n";
        seek $fh, 0, 0;

        binmode($fh);
        $md5->addfile($fh);

        close($fh);
    }
    my $base_hash = $md5->hexdigest;
    my $full_hash = $base_hash . "_" . $arch_suffix;
    print $tag_fh $item_header . "Hash: " . $full_hash . "\n";
    close($tag_fh);
    debug_log(sprintf "calc_image_md5(): returning '%s'\n", $full_hash);

    return $full_hash;
}

sub remote_image_found {
    my $image = shift;
    my $registry_type = shift;
    my $full_url;
    if ($image =~ /:/) {
        $full_url = $image;
    } else {
        $full_url = $run{'registries'}{$registry_type}{'url-details'}{'dest-image-url'} . ":" . $image;
    }
    debug_log(sprintf "Checking for remote workshop image: %s...\n", $full_url);
    my $skopeo_url;
    if (($full_url =~ /^dir:/) || ($full_url =~ /^docker:\/\//)) {
        $skopeo_url = $full_url;
    } else {
        $skopeo_url = "docker://" . $full_url;
    }
    my $skopeo_auth = "";
    if ($registry_type eq "private") {
        $skopeo_auth = "--authfile=" . $run{'registries'}{$registry_type}{'pull-token'};
    }
    my $cmd = "skopeo inspect --no-tags --raw " . $skopeo_auth . " --tls-verify=" . $run{'registries'}{$registry_type}{'tls-verify'} . " " . $skopeo_url . " 2>&1";
    debug_log(sprintf "running: %s\n", $cmd);
    ($cmd, my $output, my $cmd_rc) = run_cmd($cmd);
    if ($cmd_rc == 0) {
        debug_log(sprintf "found\n");
        return 1;
    } else {
        debug_log(sprintf "missing\n");
        return 0;
    }
}

sub local_image_found {
    my $image = shift;
    my $registry_type = shift;
    my $full_url;
    if ($image =~ /:/) {
        $full_url = $image;
    } else {
        $full_url = $run{'registries'}{$registry_type}{'url-details'}{'source-image-url'} . ":" . $image;
    }
    debug_log(sprintf "Checking for local workshop image: %s...\n", $full_url);
    my $cmd = "buildah images " . $full_url;
    debug_log(sprintf "cmd:\n%s\n\n", $cmd);
    ($cmd, my $output, my $cmd_rc) = run_cmd($cmd);
    debug_log(sprintf "output:\n%s\n\n", $output);
    if ($cmd_rc == 0) {
        debug_log(sprintf "found\n");
        return 1;
    } else {
        debug_log(sprintf "missing\n");
        debug_log(sprintf "All buildah images:\n");
        my $cmd = "buildah images";
        ($cmd, my $output, my $cmd_rc) = run_cmd($cmd);
        debug_log(sprintf "output:\n%s\n\n", $output);
        return 0;
    }
}

sub workshop_build_image {
    my $userenv = shift;
    my $registry_type = shift;
    my $bench_or_tool = shift;
    my $workshop_base_cmd = shift;
    my $stage = shift;
    my $userenv_arg = shift;
    die "workshop_build_image(): userenv_arg must be defined\n" if !defined $userenv_arg;
    my $req_args = shift;
    my $tag = shift;
    my $skip_update = shift;
    if (!defined $skip_update) {
        log_print "skip_update was not defined, so setting to false\n";
        $skip_update = "false";
    }
    my $proj;
    if (defined $run{'registries'}{$registry_type}{'url-details'}{'project'}) {
        $proj = $run{'registries'}{$registry_type}{'url-details'}{'host'} . "/" . $run{'registries'}{$registry_type}{'url-details'}{'project'};
    } else {
        $proj = $run{'registries'}{$registry_type}{'url-details'}{'host'};
    }
    my $workshop_build_cmd = $workshop_base_cmd
                             . " --skip-update " . $skip_update
                             . " " . $userenv_arg
                             . " " . $req_args
                             . " --proj " . $proj
                             . " --label " . $run{'registries'}{$registry_type}{'url-details'}{'label'}
                             . " --tag " . $tag;
    debug_log(sprintf "Going to generate a new engine container image with this workshop cmd:\n\n %s\n", $workshop_build_cmd);
    ($workshop_build_cmd, my $workshop_output, my $workshop_rc) = run_cmd($workshop_build_cmd);
    my @workshop_output = split(/\n/, $workshop_output);
    my $workshop_output_file = $workshop_build_dir . $userenv . "__" . $bench_or_tool . "__stage-" . $stage . "." . $tag . ".stdout.txt";
    my $fh = open_write_text_file($workshop_output_file) || die "Failed to open " . $workshop_output_file . " for writing\n";
    printf $fh "%s\n", join("\n", @workshop_output);
    close($fh);
    if ($workshop_rc > 0) {
        log_print sprintf "Workshop build failed: rc=%d\n", $workshop_rc;
        log_print sprintf "Workshop build command: %s\n", $workshop_build_cmd;
        log_print "Workshop build output:\n";
        log_print sprintf "%s\n", join("\n", @workshop_output);
        exit 1;
    }
    debug_log(sprintf "%s\n", join("\n", @workshop_output));
    # Becasue there can be a lot of non-JSON debug/info stuff in the output before the
    # actual JSON, find the JSON by starting at the end and scanning backwards
    my $workshop_json = "";
    for (my $i = scalar @workshop_output - 1; $i > 0; $i--) {
        $workshop_json = $workshop_output[$i] . $workshop_json;
        # Break out if we found all of the JSON
        # In this case the JSON begins with an array '['
        last if ($workshop_output[$i] eq "[");
    }
    my $coder = JSON::XS->new;
    my $workshop_ref = $coder->decode($workshop_json);
    my $workshop_image_id = $$workshop_ref[0]{'id'};
    return $workshop_image_id;
}

sub delete_local_image {
    my $image = shift;
    my $registry_type = shift;
    my $full_url;
    if ($image =~ /:/) {
        $full_url = $image;
    } else {
        $full_url = $run{'registries'}{$registry_type}{'url-details'}{'source-image-url'} . ":" . $image;
    }
    if (!local_image_found($image, $registry_type)) {
        log_print sprintf "ERROR: delete_local_image(): could not find local image [%s] before delete\n", $full_url;
        log_print sprintf "imgae: [%s]\n", $image;
        log_print sprintf "full_url: [%s]\n", $full_url;
        log_print sprintf "source-image-url: [%s]\n", $run{'source-image-url'};
        exit 1;
    }
    debug_log(sprintf "Deleting local image %s\n", $full_url);
    my $cmd = "buildah";
    $cmd .= " rmi " . " " . $full_url;
    ($cmd, my $output, my $cmd_rc) = run_cmd($cmd);
    if ($cmd_rc != 0) {
        log_print sprintf "ERROR: delete_local_image(): rmi command [%s] failed with %d\nOutput:\n%s\n\n",
                          $cmd, $cmd_rc, $output;
        exit 1;
    }
}

sub push_local_image {
    my $image_tag = shift;
    my $registry_type = shift;
    my $full_src_url = $run{'registries'}{$registry_type}{'url-details'}{'source-image-url'} . ":" . $image_tag;
    my $full_dest_url = $run{'registries'}{$registry_type}{'url-details'}{'dest-image-url'} . ":" . $image_tag;
    if ($full_dest_url =~ /^dir:/) {
        $full_dest_url =~ /^dir:(.*)/;
        my $image_dir = $1;
        if (! -d $image_dir) {
            log_print sprintf "Creating local registry directory: %s\n", $image_dir;
            make_path($image_dir, { verbose => 1, error => \my $err } );
            if ($err && @$err) {
                log_print "make_path: encountered errors:\n";
                for my $diag (@$err) {
                    log_print Dumper $diag;
                }
            }
        }
    }
    if (!local_image_found($image_tag, $registry_type)) {
        die "ERROR: push_local_image(): could not find local image before push ($image_tag)";
    }
    my $cmd = "buildah";
    if (exists $run{'registries'}{$registry_type}{'push-token'}) {
        $cmd .= " --authfile " . $run{'registries'}{$registry_type}{'push-token'};
    }
    $cmd .= " push --tls-verify=" . $run{'registries'}{$registry_type}{'tls-verify'} . " " . $full_src_url . " " . $full_dest_url;

    my $attempts = 1;
    my $max_attempts = 5;
    my $cmd_rc;
    my $output;
    my $retry_loop = 1;
    while ($retry_loop == 1) {
        debug_log(sprintf "attempt %d/%d for 'buildah push' command '%s'\n", $attempts, $max_attempts, $cmd);
        ($cmd, $output, $cmd_rc) = run_cmd($cmd);
        if ($cmd_rc != 0) {
            if ($attempts >= $max_attempts) {
                debug_log(sprintf "'buildah push' attempts exceeded max_attempts of %d\n", $max_attempts);
                $retry_loop = 0;
            } else {
                my $do_retry = 0;
                if (($output =~ /502 Bad Gateway/) || ($output =~ /502 \(Bad Gateway\)/)) {
                    debug_log("'buildah push' failed with '502 Bad Gateway'\n");
                    $do_retry = 1;
                } elsif ($output =~ /too many requests/) {
                    debug_log("'buildah push' failed with 'too many requests'\n");
                    $do_retry = 1;
                } else {
                    debug_log("'buildah push' failed for an unhandled reason\n");
                }
                if ($do_retry) {
                    debug_log("'buildah push' failure type allows for a retry\n");
                    debug_log(sprintf "sleeping for %d seconds to let the registry recover\n", $attempts);
                    sleep $attempts;
                    debug_log("incrementing attempts counter\n");
                    $attempts++;
                } else {
                    debug_log("'buildah push' failure type does not allow for a retry\n");
                    $retry_loop = 0;
                }
            }
        } else {
            $retry_loop = 0;
        }
    }
    if ($cmd_rc != 0) {
        log_print sprintf "ERROR: push_local_image(): push command [%s] failed with %d\nOutput:\n%s\n\n",
                          $cmd, $cmd_rc, $output;
        if ($attempts > 1) {
            log_print sprintf "ERROR: push_local_image() failed after %d/%d attempts\n", $attempts, $max_attempts;
        }
        exit 1;
    } elsif ($attempts > 1) {
        log_print sprintf "WARNING: push_local_image(): succeeded after %d/%d attempts\n", $attempts, $max_attempts;
    }
    if (!remote_image_found($image_tag, $registry_type)) {
        log_print "WARNING: push_local_image(): failed to find remote image after push...retrying!\n";
        my $found_it = 0;
        for (my $i=1; $i<=20; $i++) {
            sleep 3;

            if (remote_image_found($image_tag, $registry_type)) {
                $found_it = 1;
                last;
                log_print sprintf "NOTICE: push_local_image(): found image on retry attempt number %d\n", $i;
            } else {
                log_print sprintf "NOTICE: push_local_image(): failed to find image on retry attempt number %d\n", $i;
            }
        }

        if (!$found_it) {
            die "ERROR: push_local_image(): could not find remote image after push ($image_tag)";
        }
    }
}

sub build_reqs {
    my $req_ref = shift;
    my $userenv = shift;
    my $benchmark = shift;
    return if (!$use_workshop);

    # Build an ordered list of requirements.  What order?  That depends.
    # We want the first requirements to be ones that are most commonly
    # used by many users, while also not being updated very often, followed
    # by lesser common or requirments that have their content changed more
    # frequently.
    #
    # If there is a requirment that is widely used and its contents might
    # change frequently, we should consider sourcing this requirement
    # after a container image is provisioned, but that generally only works
    # if the contents of the requirment is of type "files".  An example of
    # this is the engine-script from the engine subdirectory and various
    # scripts from benchmarks and tools..
    #
    # Why is this order important?  We build container images incrementally,
    # with the smallest one containing only the userenv, and build bigger and
    # bigger images, each with a new requirement.  Ultimately, a user would like
    # to match an existing built image with all of their requirments, but if
    # that does not exist, we want to match an imagewith as many requirements
    # as possible and add only what we need.

    # The most common requirment is expected to be the toolbox.
    my $tb_req_file = $config_dir . "/toolbox-req.json";
    my %tb_req = (
                    'workshop' => {
                        'schema' => {
                            'version' => '2020.03.02'
                        }
                    },
                    'userenvs' => [
                        {
                            'name' => 'default',
                                'requirements' => [
                                    'toolbox'
                                ]
                        }
                    ],
                    'requirements' => [
                        {
                            'name' => 'toolbox',
                            'type' => 'files',
                            'files_info' => {
                                'files' => [
                                    {
                                        'src' => $ENV{'TOOLBOX_HOME'},
                                        'dst' => '/opt/toolbox'
                                    }
                                ]
                            }
                        }
                    ]
                );
    if (put_json_file($tb_req_file, \%tb_req) > 0) {
        log_print "build_container_image(): put_json_file() failed\n";
        exit 1;
    }
    push (@$req_ref, "--requirement " . $tb_req_file);
    # The second toolbox req ensures the proper dependencies are installed
    push (@$req_ref, "--requirement " . $ENV{'TOOLBOX_HOME'} .  "/workshop.json");

    # ensure the proper python libraies are installed that roadblock needs
    push (@$req_ref, "--requirement " . $run{'roadblock-dir'} .  "/workshop.json");

    push (@$req_ref, "--requirement " . $rickshaw_project_dir . "/engine/workshop.json");
    foreach my $utility (@utilities) {
        if (exists $run{$utility . '-dir'}) {
            my $utility_req_file = $run{$utility . '-dir'} . "/workshop.json";
            if (-e $utility_req_file) {
                push (@$req_ref, "--requirement " . $utility_req_file);
            }
        }
    }
    push (@$req_ref, "--requirement " . $bench_dirs{$benchmark} . "/workshop.json");
}

sub quay_image_refresh_formatted_timestamp {
    # format a timestamp into human readable format
    my $timestamp = shift;

    return scalar localtime($timestamp);
}

sub source_container_image {
    # Ensure that the container image we need is either already in the container registry,
    # or build and push the image to the registry
    my $userenv = shift;
    my $benchmark = shift;
    my $container_arch = shift;
    my $image; # What gets returned
    my @local_images;

    # variables for tracking operation duration
    my $begin;
    my $end;

    # load the userenv as early as possible so we can determine if it
    # is a public or private image

    # first we need to find where it is -- is it internal (to
    # rickshaw) or is it provided by an external userenv library.
    my $userenv_file_path;

    # let's look externally first in case somebody has tried to
    # override an internal version
    if (exists $run{'external-userenvs-dir'}) {
        if (opendir(TOP_USERENV_DIR_DH, $run{'external-userenvs-dir'})) {
            my @top_userenvs_dir_entries = readdir(TOP_USERENV_DIR_DH);
            close(TOP_USERENV_DIR_DH);

            foreach my $userenv_dir (@top_userenvs_dir_entries) {
                if (($userenv_dir eq ".") || ($userenv_dir eq "..")) {
                    next;
                }
                $userenv_dir = $run{'external-userenvs-dir'} . "/" . $userenv_dir;
                if (-d $userenv_dir) {
                    if (opendir(BOTTOM_USERENV_DIR_DH, $userenv_dir)) {
                        my @bottom_userenvs_dir_entries = readdir(BOTTOM_USERENV_DIR_DH);
                        close(BOTTOM_USERENV_DIR_DH);

                        foreach my $userenv_dir_entry (@bottom_userenvs_dir_entries) {
                            if (($userenv_dir_entry eq ".") || ($userenv_dir_entry eq "..")) {
                                next;
                            }
                            if ($userenv_dir_entry eq ($userenv . ".json")) {
                                $userenv_file_path = $userenv_dir . "/" . $userenv_dir_entry;
                                log_print sprintf "Found userenv %s in external userenv directory at %s\n", $userenv, $userenv_file_path;
                            }
                        }
                    } else {
                        die "ERROR: Could not open directory in the external userenvs directory: " . $userenv_dir . "\n";
                    }
                }
            }
        } else {
            die "ERROR: Could not open external userenvs directory: " . $run{'external-userenvs-dir'} . "\n";
        }
    }

    my $internal_userenv_file_path = $rickshaw_project_dir . "/userenvs/" . $userenv . ".json";
    if (! defined $userenv_file_path && -e $internal_userenv_file_path) {
        $userenv_file_path = $internal_userenv_file_path;
        log_print sprintf "Found userenv %s in rickshaw directory at %s\n", $userenv, $userenv_file_path;
    }

    if (! defined $userenv_file_path) {
        die "ERROR: Could not locate the requested userenv: " . $userenv . "\n";
    }

    (my $rc, my $userenv_ref) = get_json_file($userenv_file_path);
    if ($rc != 0) {
        die "ERROR: Could not load userenv JSON file for '" . $userenv . "' due to non-zero return code " . $rc . ".  Are you sure this is a supported userenv?\n";
    }

    my $registry_type = "public";
    if (exists $$userenv_ref{'userenv'}{'origin'}{'requires-pull-token'}) {
        if ($$userenv_ref{'userenv'}{'origin'}{'requires-pull-token'} eq "true") {
            $registry_type = "private";
        }
    }
    if ($registry_type eq "public") {
        log_print sprintf "Userenv %s does not require a pull token so it comes from a public registry repo.\n", $userenv;
    } elsif ($registry_type eq "private") {
        log_print sprintf "Userenv %s does require a pull token so it comes from a private registry repo.\n", $userenv;
    }

    if (! exists $run{'registries'}{$registry_type}) {
        die "ERROR: The requested userenv is a " . $registry_type . " image but there is not a defined " . $registry_type . " engine registry!\n";
    }

    $workshop_base_cmd =
    $run{'workshop-dir'} . "/workshop.pl" .
    " --log-level verbose " .
    " --config " . $cs_conf_file .
    " --param %bench-dir%=" . $bench_dirs{$benchmark} .
    " --param %engine-dir%=" . $rickshaw_project_dir . "/engine/" .
    " --param %rickshaw-dir%=" . $rickshaw_project_dir .
    " --reg-tls-verify=" . $run{'registries'}{$registry_type}{'tls-verify'} .
    " --registries-json=" . $run{'registries-json'} .
    " 2>&1";

    log_print sprintf "Sourcing container image for userenv '%s' (%s) and benchmark/tool '%s'; this may take a few minutes\n", $userenv, $registry_type, $benchmark;

    my @requirements;
    build_reqs(\@requirements, $userenv, $benchmark);

    # First build a workshop-cmd args containing: (userenv_arg, req_args, tag), starting with the base userenv only (has no req_args),
    # then each additional item in the list is a userenv arg matching the md5sum of the previous image, plus one more requirement.
    # Keep adding to this list until @requirements is empty.
    my @workshop_args;
    my $userenv_arg;
    my $count = 0;
    my $userenv_image = $$userenv_ref{'userenv'}{'origin'}{'image'} . ":" . $$userenv_ref{'userenv'}{'origin'}{'tag'};
    while (scalar @requirements > 0) {
        my $req_arg;
        my $skip_update;
        if ($count == 0) {
            $userenv_arg = " --userenv " . $userenv_file_path;
            $req_arg = "";
            if (exists $$userenv_ref{'userenv'}{'origin'}{'update-policy'} and $$userenv_ref{'userenv'}{'origin'}{'update-policy'} eq 'never') {
                $skip_update = "true";
            } else {
                $skip_update = "false";
            }
        } else {
            $req_arg = shift(@requirements);
            $skip_update = "true";
        }

        # keep separate cs_conf_file contents before and after md5
        # calculation so that the quay.io image expiration value is
        # not factored into the image hash
        %cs_conf = (
                'workshop' => {
                    'schema' => {
                        'version' => '2020.04.30'
                    }
                },
                'config' => {
                    'entrypoint' => [ "/bin/sh", "-c", "/usr/local/bin/bootstrap" ],
                    'envs' => [ 'TOOLBOX_HOME=/opt/toolbox' ]
                }
            );
        if (put_json_file($cs_conf_file, \%cs_conf) > 0) {
            log_print sprintf "put_json_file(): initial %s: failed\n", $cs_conf_file;
            exit 1;
        }
        my $tag = calc_image_md5($workshop_base_cmd, $userenv_arg, $req_arg, $container_arch, $userenv, $benchmark, scalar(@workshop_args) + 1);
        $cs_conf{'config'}{'labels'} = [ 'quay.expires-after=' . $run{'registries'}{'public'}{'quay-expiration-length'} ];
        if (put_json_file($cs_conf_file, \%cs_conf) > 0) {
            log_print sprintf "put_json_file(): update %s: failed\n", $cs_conf_file;
            exit 1;
        }

        my %args = ( 'userenv' => $userenv_arg, 'reqs' => $req_arg, 'tag' => $tag, 'skip-update' => $skip_update );
        push (@workshop_args, \%args);

        $count++;
        if (scalar @requirements > 0) {
            # Create a new userenv which just refers to the image just verified/built,,
            # which will be used as the userenv for the next image in this loop.
            #
            # We need some info from the original userenv, primarily
            # userenv.name and userenv.properties.packages, but we'll
            # copy all of it and only change what we need.
            #my $userenv_ref = get_json_file($rickshaw_project_dir . "/userenvs/" . $userenv . ".json");
            delete $$userenv_ref{'requirements'};
            my @reqs = ();
            @$userenv_ref{'requirements'} = \@reqs;
            $$userenv_ref{'userenv'}{'origin'}{'image'} = $run{'registries'}{$registry_type}{'url-details'}{'dest-image-url'};
            $$userenv_ref{'userenv'}{'origin'}{'tag'} = $tag;
            if (defined $$userenv_ref{'userenv'}{'origin'}{'build-policy'}) {
                delete $$userenv_ref{'userenv'}{'origin'}{'build-policy'};
            }
            my $userenv_file = $config_dir . "/userenv-" . $tag . ".json";
            put_json_file($userenv_file, $userenv_ref);
            $userenv_arg = " --userenv " . $userenv_file;
        }
    }

    debug_log(sprintf "workshop_args:\n" . Dumper \@workshop_args);

    my $num_images = scalar @workshop_args;
    my $i;
    if ($workshop_force_builds eq "false") {
        # Now that we have all the info to build any stage of the container image we could need,
        # search for existing container images, starting with the most complete image first.
        log_print sprintf "Searching for existing stages (1 to %d, %d being most complete)\n", $num_images, $num_images;
        $i = $num_images - 1;
        while ($i >= 0) {
            debug_log(sprintf "Checking for stage number %d (of %d)\n", $i + 1, $num_images);
            if (!remote_image_found($workshop_args[$i]{'tag'}, $registry_type)) {
                if (!local_image_found($workshop_args[$i]{'tag'}, $registry_type)) {
                    $i--;
                    next;
                } else {
                    log_print "\tCould not find image remotely but found it locally so pushing it...\n";
                    $begin = time();
                    push_local_image($workshop_args[$i]{'tag'}, $registry_type);
                    $end = time();
                    log_print sprintf "\t\tPushing took %d seconds\n", $end - $begin;
                    last;
                }
            } else {
                last;
            }
        }
        if ($i == -1) {
            log_print "Did not find any existing stages\n";
        } elsif ($i < $num_images - 1) {
            log_print sprintf "Found stage number %d (of %d), need to build %d stage(s)\n", $i + 1, $num_images, $num_images - 1 - $i;
        } elsif ($i == $num_images - 1) {
            log_print sprintf "Found most complete stage (number %d)\n", $i + 1;
        } else {
            log_print sprintf "Something went wrong, stage number: %d, num_images: %d\n", $i + 1, $num_images;
            exit 1;
        }
    } elsif ($workshop_force_builds eq "true") {
        log_print sprintf "Image building is forced, checking if any of the needed stages were already built during this run (1 to %d, %d being most complete)\n", $num_images, $num_images;
        $i = $num_images - 1;
        while ($i >= 0) {
            debug_log(sprintf "Checking for stage number %d (of %d)\n", $i + 1, $num_images);
            if (exists $workshop_built_tags{$workshop_args[$i]{'tag'}}) {
                if (!remote_image_found($workshop_args[$i]{'tag'}, $registry_type)) {
                    if (!local_image_found($workshop_args[$i]{'tag'}, $registry_type)) {
                        log_print sprintf "ERROR: Cannot find the image I was previously forced to build (%s)", $workshop_args[$i]{'tag'};
                        exit 1;
                    } else {
                        push_local_image($workshop_args[$i]{'tag'}, $registry_type);
                        last;
                    }
                } else {
                    last;
                }
            } else {
                $i--;
                next;
            }
        }
        if ($i == -1) {
            log_print "Did not find any existing stages built during this run\n";
        } elsif ($i < $num_images - 1) {
            log_print sprintf "Found stage number %d (of %d) built during this run, need to build %d stage(s)\n", $i + 1, $num_images, $num_images - 1 - $i;
        } elsif ($i == $num_images - 1) {
            log_print sprintf "Found most complete stage built during this run (number %d)\n", $i + 1;
        } else {
            log_print sprintf "Something went wrong searching for stages built during this run, stage number: %d, num_images: %d\n", $i + 1, $num_images;
            exit 1;
        }
    }
    $image = $run{'registries'}{$registry_type}{'url-details'}{'dest-image-url'} . ":" . $workshop_args[$i]{'tag'};
    # After finding the most complete image, build any "more" complete images until "most"
    # complete is built.
    $i++;
    if ($i == 0) {
        # The first stage pulls a userenv image (like fedora, stream, etc), and that
        # image needs to be deleted later, so save a reference to it here
        push(@local_images, $userenv_image);
    }
    my $x = 0;
    my $refresh_expiration;
    if (defined $quay_refresh_expiration_tokens{$registry_type} && defined $run{'registries'}{$registry_type}{'quay-refresh-expiration-api-url'}) {
        if ($run{'registries'}{$registry_type}{'quay-expiration-length'} =~ m/([1-9][0-9]*)w/) {
            #                               weeks   days/week   hours/day   min/hour   seconds/min
            $refresh_expiration = time() + ($1    * 7         * 24        * 60       * 60);
        } elsif ($run{'registries'}{$registry_type}{'quay-expiration-length'} =~ m/([1-9][0-9]*)d/) {
            #                               days   hours/day   min/hour   seconds/min
            $refresh_expiration = time() + ($1     * 24        * 60       * 60);
        } else {
            log_print "Failed to determine quay image expiration\n";
            exit 1;
        }

        log_print sprintf "Going to refresh image expiration with this value: %d (%s)\n", $refresh_expiration, quay_image_refresh_formatted_timestamp($refresh_expiration);
    }
    while ($x < $i) {
        log_print sprintf "Processing stage %d (%s)...\n", $x + 1, $workshop_args[$x]{'tag'};
        if (defined $quay_refresh_expiration_tokens{$registry_type} && defined $run{'registries'}{$registry_type}{'quay-refresh-expiration-api-url'}) {
            if (remote_image_found($workshop_args[$x]{'tag'}, $registry_type)) {
                my $max_refresh_attempts = 3;
                my $refresh_attempts;

                my $query_cmd   = 'curl --silent' .
                                  ' -X GET -H "Authorization: Bearer ' . $quay_refresh_expiration_tokens{$registry_type} . '"' .
                                  ' "' . $run{'registries'}{$registry_type}{'quay-refresh-expiration-api-url'} .
                                  '/tag/?onlyActiveTags=true&specificTag=' . $workshop_args[$x]{'tag'} . '"';

                my $current_expiration;

                $refresh_attempts = 1;
                while ($refresh_attempts <= $max_refresh_attempts) {
                    $refresh_attempts += 1;

                    debug_log(sprintf "executing quay API call: %s\n", $query_cmd);
                    ($query_cmd, my $query_status, my $query_rc) = run_cmd($query_cmd);
                    chomp($query_status);

                    my $failed_attempt = 0;
                    if ($query_rc == 0) {
                        my $coder = JSON::XS->new;
                        my $query_ref;
                        eval {
                            $query_ref = $coder->decode($query_status);
                        };
                        if ($@) {
                            my $error_message = $@;
                            log_print "Caught an exception while attempting to decode JSON: $error_message";
                            log_print sprintf "JSON contents:\n%s\n", $query_status;
                            $failed_attempt = 1;
                        } else {
                            if (defined $$query_ref{'tags'}[0]) {
                                $current_expiration = $$query_ref{'tags'}[0]{'end_ts'};
                                last;
                            } else {
                                log_print "\tTag information returned from query is incomplete\n";
                                log_print Dumper $query_ref;
                                $failed_attempt = 1;
                            }
                        }
                    } else {
                        $failed_attempt = 1;
                    }

                    if ($failed_attempt) {
                        if ($refresh_attempts > $max_refresh_attempts) {
                            log_print sprintf "\tFailed to query for tag information on %d attempts\n", $max_refresh_attempts;

                            if ($run{'registries'}{$registry_type}{'quay-refresh-expiration-require-success'} eq "true") {
                                log_print "\tExpiration refresh success is required, exiting\n";
                                exit 1;
                            } else {
                                log_print "\tExpiration refresh success is not required, continuing\n";
                            }
                        } else {
                            sleep 1;
                        }
                    }
                }

                if (!defined $current_expiration) {
                    log_print "\tSkipping expiration refresh because tag query failed\n";
                } else {
                    my $time_buffer_days = 1;
                    #                  days                   hours/day   min/hour   seconds/min
                    my $time_buffer = ($time_buffer_days    * 24        * 60       * 60);
                    if ($current_expiration >= $refresh_expiration) {
                        log_print sprintf "\tThe current expiration (%d / %s) is greater than or equal to the refresh expiration so not refreshing\n", $current_expiration, quay_image_refresh_formatted_timestamp($current_expiration);
                    } elsif (($refresh_expiration - $current_expiration) <= $time_buffer) {
                        log_print sprintf "\tSkipping expiration refresh because the current expiration (%d / %s) is less than %d day(s) (%d seconds) older than the new expiration\n", $current_expiration, quay_image_refresh_formatted_timestamp($current_expiration), $time_buffer_days, $time_buffer;
                    } else {
                        my $refresh_cmd = 'curl --silent' .
                                          ' -X PUT -H "Authorization: Bearer ' . $quay_refresh_expiration_tokens{$registry_type} . '"' .
                                          ' -H "Content-type: application/json" -d \'{ "expiration": ' . $refresh_expiration . ' }\'' .
                                          ' ' . $run{'registries'}{$registry_type}{'quay-refresh-expiration-api-url'} . '/tag/' . $workshop_args[$x]{'tag'};

                        $refresh_attempts = 1;
                        while ($refresh_attempts <= $max_refresh_attempts) {
                            $refresh_attempts += 1;

                            debug_log(sprintf "executing quay API call: %s\n", $refresh_cmd);
                            ($refresh_cmd, my $refresh_status, my $refresh_rc) = run_cmd($refresh_cmd);
                            chomp($refresh_status);

                            if (($refresh_rc == 0) && ($refresh_status eq "\"Updated\"")) {
                                log_print sprintf "\tRefreshed expiration (was %d / %s)\n", $current_expiration, quay_image_refresh_formatted_timestamp($current_expiration);
                                last;
                            } else {
                                if ($refresh_attempts > $max_refresh_attempts) {
                                    log_print sprintf "\tFailed to refresh expiration on %d attempts (currently %d / %s)\n", $max_refresh_attempts, $current_expiration, quay_image_refresh_formatted_timestamp($current_expiration);

                                    if ($run{'registries'}{$registry_type}{'quay-refresh-expiration-require-success'} eq "true") {
                                        log_print "\tExpiration refresh success is required, exiting\n";
                                        exit 1;
                                    } else {
                                        log_print "\tExpiration refresh success is not required, continuing\n";
                                    }
                                } else {
                                    sleep 1;
                                }
                            }
                        }
                    }
                }
            } else {
                log_print "\tskipping expiration refresh because remote image does not exist (!!)\n";
            }
        }
        log_print "\tReady\n";
        $x++;
    }
    while ($i <= $num_images - 1) {
        log_print sprintf "Processing stage %d (%s)...\n", $i + 1, $workshop_args[$i]{'tag'};
        $begin = time();
        workshop_build_image($userenv, $registry_type, $benchmark, $workshop_base_cmd, $i + 1, $workshop_args[$i]{'userenv'}, $workshop_args[$i]{'reqs'}, $workshop_args[$i]{'tag'}, $workshop_args[$i]{'skip-update'});
        $end = time();
        log_print sprintf "\tBuilding took %d seconds\n", $end - $begin;
        # it is possible that the image was built and pushed somewhere
        # else while we were building it, so check if that happend to
        # avoid pushing over an existing image; it is possible that
        # this could happen frequently when running in the CI
        # environment since there is a potential race condition
        # between the multiple jobs that are running in parallel; even
        # though we already took the time to build the image there is
        # the potential for significant time (and bandwidth) savings
        # by avoiding an unnecessary push
        if (remote_image_found($workshop_args[$i]{'tag'}, $registry_type)) {
            log_print sprintf "\tSkipping push because image now exists remotely\n";
        } else {
            $begin = time();
            push_local_image($workshop_args[$i]{'tag'}, $registry_type);
            $end = time();
            log_print sprintf "\tPushing took %d seconds\n", $end - $begin;
        }
        $workshop_built_tags{$workshop_args[$i]{'tag'}} = 1;
        push(@local_images, $workshop_args[$i]{'tag'});
        $image = $run{'registries'}{$registry_type}{'url-details'}{'dest-image-url'} . ":" . $workshop_args[$i]{'tag'};
        $i++;
    }
    my $num_local_images = scalar @local_images;
    if ($num_local_images > 0) {
        log_print sprintf "Deleting %d local images\n", $num_local_images;
        while (scalar @local_images) {
            delete_local_image(pop(@local_images), $registry_type);
        }
    }
    log_print sprintf "Finished sourcing container image for userenv '%s' (%s) and benchmark/tool '%s'\n", $userenv, $registry_type, $benchmark;
    if ($registry_type eq "private") {
        $image .= "::" . $run{'registries'}{$registry_type}{'pull-token'};
    }
    return $image;
}

###############################################################################
# Main
###############################################################################

my $input_file;
my $output_file;
my $log_level;

GetOptions(
    "input=s"     => \$input_file,
    "output=s"    => \$output_file,
    "log-level=s" => \$log_level,
) or die "Usage: rickshaw-source-images --input <file> --output <file> [--log-level <level>]\n";

if (!defined $input_file || !defined $output_file) {
    die "Usage: rickshaw-source-images --input <file> --output <file> [--log-level <level>]\n";
}

if (defined $log_level && $log_level eq "debug") {
    $toolbox::logging::debug = 1;
}

# Read input JSON
(my $rc, my $input_ref) = get_json_file($input_file);
if ($rc != 0 || !defined $input_ref) {
    die "Failed to read input JSON file: $input_file\n";
}
# Note: input schema validation is deferred until $rickshaw_project_dir is known (below)

# Reconstruct global state from input JSON
%run = ();
$run{'registries'} = $$input_ref{'registries'};
$run{'workshop-dir'} = $$input_ref{'workshop'}{'dir'};
$run{'roadblock-dir'} = $$input_ref{'roadblock-dir'};
$run{'registries-json'} = $$input_ref{'registries-json'};
if (exists $$input_ref{'external-userenvs-dir'}) {
    $run{'external-userenvs-dir'} = $$input_ref{'external-userenvs-dir'};
}

$rickshaw_project_dir = $$input_ref{'dirs'}{'rickshaw'};
my $source_images_input_schema_file = $rickshaw_project_dir . "/schema/source-images-input.json";
my $source_images_output_schema_file = $rickshaw_project_dir . "/schema/source-images-output.json";
# Validate input now that we know the schema path
($rc, undef) = get_json_file($input_file, $source_images_input_schema_file);
if ($rc != 0) {
    die "Input JSON failed schema validation: $input_file\n";
}
$config_dir = $$input_ref{'dirs'}{'config'};
$workshop_build_dir = $$input_ref{'dirs'}{'workshop-build'};
$arch = $$input_ref{'arch'};

%bench_dirs = %{$$input_ref{'bench-dirs'}};
@utilities = @{$$input_ref{'utilities'}};
$use_workshop = $$input_ref{'use-workshop'};
$workshop_force_builds = $$input_ref{'workshop'}{'force-builds'};
$cs_conf_file = $$input_ref{'cs-conf-file'};

# Reconstruct utility dirs into %run
foreach my $utility (@utilities) {
    if (exists $$input_ref{'utility-dirs'}{$utility}) {
        $run{$utility . '-dir'} = $$input_ref{'utility-dirs'}{$utility};
    }
}

# Load quay refresh expiration tokens from files referenced in registries
for my $registry_type ('public', 'private') {
    if (exists $run{'registries'}{$registry_type}{'quay-refresh-expiration-token-file'}) {
        my $token_file = $run{'registries'}{$registry_type}{'quay-refresh-expiration-token-file'};
        if (open(my $fh, "<", $token_file)) {
            $quay_refresh_expiration_tokens{$registry_type} = <$fh>;
            chomp($quay_refresh_expiration_tokens{$registry_type});
            close $fh;
            log_print sprintf "Loaded %s registry quay refresh expiration token from %s\n", $registry_type, $token_file;
        } else {
            log_print sprintf "Failed to load %s registry quay refresh expiration token from %s\n", $registry_type, $token_file;
            exit 1;
        }
    }
}

# Process image-ids
my %image_ids = %{$$input_ref{'image-ids'}};

log_print "rickshaw-source-images: starting image sourcing\n";
debug_log(sprintf "image_ids (before):\n" . Dumper \%image_ids);

foreach my $bench_or_tool (sort (keys %image_ids)) {
    log_print sprintf "Working on %s benchmark or tool\n", $bench_or_tool;
    foreach my $userenv (sort (keys %{ $image_ids{$bench_or_tool} })) {
        log_print sprintf "Working on %s userenv\n", $userenv;
        my $image = source_container_image($userenv, $bench_or_tool, $arch);
        if (!defined $image) {
            die "Could not get valid image for container image build for userenv [" . $userenv . "] and benchmark [" . $bench_or_tool . "]\n";
        }
        log_print sprintf "Image is: %s\n", $image;
        $image_ids{$bench_or_tool}{$userenv}{'image'} = $image;
    }
}

debug_log(sprintf "image_ids (after):\n" . Dumper \%image_ids);

# Write output JSON with populated image URLs
my %output = ( 'image-ids' => \%image_ids );
if (put_json_file($output_file, \%output, $source_images_output_schema_file) > 0) {
    die "Failed to write output JSON file: $output_file\n";
}

log_print "rickshaw-source-images: image sourcing complete\n";
exit 0;
