#!/usr/local/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
exec 2>&1

echo "BASH_VERSION=${BASH_VERSION}"

test -e /etc/profile && . /etc/profile

if [ ! -e /usr/local/bin/engine-script-library ]; then
    echo "ERROR: Could not location engine-library"
else
    echo "source engine-script-library: BEGIN"
    source engine-script-library
    echo "source engine-script-library: END"
fi

# Depending on how engine-script is started, "/usr/local/bin" is not
# always in the $PATH
PATH="/usr/local/bin:$PATH"

echo "engine-script env:"
env
echo "engine-script params:"
echo "$@"
echo
echo os-release:
cat /etc/os-release
echo
echo "uname:"
uname -a
echo
version=20200509
echo "version: $version"
echo

leader=controller
load_json_setting "roadblock.timeouts.default" default_timeout
load_json_setting "roadblock.timeouts.collect-sysinfo" collect_sysinfo_timeout
process_opts
validate_core_env
setup_core_env # roadblocks may be used after this

if ! pushd $cs_dir; then
    abort_error "Could not chdir to $cs_dir" engine-init-begin
    exit 1
fi

if [ "${cpu_partitioning}" == "1" ]; then
    if [ -z "${HK_CPUS}" ]; then
        abort_error "cpu-partitioning is enabled but HK_CPUS is empty" engine-init-begin
        exit 1
    fi

    if [ -z "${WORKLOAD_CPUS}" ]; then
        abort_error "cpu-partitioning is enabled but WORKLOAD_CPUS is empty" engine-init-begin
        exit 1
    fi
fi

do_roadblock engine-init-begin ${engine_script_start_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

do_roadblock engine-init-end ${engine_script_start_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}
msgs_log_file="${roadblock_msgs_dir}/engine-init-end.json"
if [ -f ${msgs_log_file} ]; then
    env_vars=`jq -r '.received[] | .payload.message."user-object"."env-vars" ' ${msgs_log_file} | grep -v null`
    if [ ! -z "${env_vars}" ]; then
        printf "Found new env vars:"
        printf "%s\n" "${env_vars}"
        eval `echo $env_vars | jq -r 'to_entries | .[] | "export " + .key + "=" + .value'`
        echo $env_vars | jq -r 'to_entries | .[] | "export " + .key + "=" + .value'
    else
        printf "Could not find new env vars\n"
    fi
else
    printf "Could not find %s\n" ${msgs_log_file}
    echo '#/bin/ls -l '$roadblock_msgs_dir
    /bin/ls -l $roadblock_msgs_dir
fi

# There are a number of env vars needed for post-processing metrics
# Do this after engine-init, as some vars can be passed to the engine in that RB
env >engine-env.txt


do_roadblock get-data-begin ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

get_data

do_roadblock get-data-end ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock collect-sysinfo-begin ${collect_sysinfo_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

collect_sysinfo

do_roadblock collect-sysinfo-end ${collect_sysinfo_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock start-tools-begin ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

start_stop_tools_opt=""
if [ "$cs_type" == "profiler" ]; then
    if [ -z "$tool_name" ]; then
        echo "env:"
        env
        exit_error "tool_name not defined [$tool_name], exiting"
    fi
start_stop_tools_opt=$tool_name
fi

start_tools $start_stop_tools_opt

do_roadblock start-tools-end ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

process_bench_roadblocks

do_roadblock stop-tools-begin ${default_timeout}
do_roadblock stop-tools-end ${default_timeout} wait-for "/usr/local/bin/engine-script-library stop_tools '$(pwd)' '${tool_stop_cmds}' '${disable_tools}' '${start_stop_tools_opt}'"

do_roadblock send-data-begin ${default_timeout}
do_roadblock send-data-end ${default_timeout} wait-for "/usr/local/bin/engine-script-library send_data '${ssh_id_file}' '${cs_dir}' '${rickshaw_host}' '${archives_dir}/${cs_label}-data.tgz'"


echo -e "\nAll client/server scripts are finished"
/bin/rm -rf $cs_dir
