name: unittest

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  blockbreaker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd util
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-html jsonschema

      - name: Run unit tests
        run: |
          cd util
          source .venv/bin/activate
          pytest -v --html=report.html --self-contained-html blockbreaker.py validate_run_file.py tests/*.py

      - name: Upload html report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: util/report.html

  rickshaw-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest pytest-html

      - name: Run unit tests
        run: |
          source .venv/bin/activate
          export RICKSHAW_HOME="${GITHUB_WORKSPACE}"
          pytest -v --html=report.html --self-contained-html tests/*.py

      - name: Upload html report
        uses: actions/upload-artifact@v4
        with:
          name: rickshaw-run-tests-report
          path: report.html
